In [85]:
import pandas as pd                        #Importing the esential libraries
import numpy as np

In [86]:
df= pd.read_excel('C:\\Users\\Anjali\\notebooks\\Untitled Folder\\HIV_0000000006.xlsx')

In [87]:
df               #reading the dataset

          WHO region  Year Number of deaths due to HIV/AIDS
0             Global  2019        690 000 [500 000–970 000]
1             Global  2018      730 000 [530 000–1 000 000]
2             Global  2017      760 000 [550 000–1 100 000]
3             Global  2016      800 000 [580 000–1 100 000]
4             Global  2015      830 000 [610 000–1 200 000]
..               ...   ...                              ...
205  Western Pacific  1994               7700 [4100–13 000]
206  Western Pacific  1993                 5500 [2900–9500]
207  Western Pacific  1992                 4000 [2100–6800]
208  Western Pacific  1991                 2900 [1600–5000]
209  Western Pacific  1990                 2100 [1100–3600]

[210 rows x 3 columns]

In [88]:
df.columns                     #viweing the total number of columns in a datset

Index(['WHO region', 'Year', 'Number of deaths due to HIV/AIDS'], dtype='object')

   Removing the Brackets AND Value inside Brackets  of the dataset

In [89]:
df['Number of deaths due to HIV/AIDS']=df['Number of deaths due to HIV/AIDS'].str.replace(r"\[.*\]","")     
df['Number of deaths due to HIV/AIDS']=df['Number of deaths due to HIV/AIDS'].str.replace(r"\ &lt ","")

 RESULTANT DATASET

In [90]:
df

          WHO region  Year Number of deaths due to HIV/AIDS
0             Global  2019                         690 000
1             Global  2018                         730 000
2             Global  2017                         760 000
3             Global  2016                         800 000
4             Global  2015                         830 000
..               ...   ...                              ...
205  Western Pacific  1994                            7700
206  Western Pacific  1993                            5500
207  Western Pacific  1992                            4000
208  Western Pacific  1991                            2900
209  Western Pacific  1990                            2100

[210 rows x 3 columns]

# Exporting the cleaned datasets to excel

In [91]:
df.to_excel('C:\\Users\\Anjali\\notebooks\\Untitled Folder\\HIV cleaned 1.xlsx',index= False , header= True)   #dataset exported to excel file

# Removal of brackets from another dataset

In [92]:
df= pd.read_excel('C:\\Users\\Anjali\\notebooks\\Untitled Folder\\HIV_0000000026,SDGHIV (1).xlsx')

In [93]:
df             #reading of the dataset

,Unnamed: 0,Unnamed: 1,Number of new HIV infections,New HIV infections (per 1000 uninfected population),New HIV infections (per 1000 uninfected population).1,New HIV infections (per 1000 uninfected population).2
0,WHO region,Year,,Both sexes,Male,Female
1,Global,2019,1 700 000 [1 200 000–2 200 000],0.22 [0.16–0.3],0.23 [0.17–0.32],0.21 [0.16-0.29]
2,Global,2018,1 700 000 [1 200 000–2 300 000],0.23 [0.17–0.31],0.24 [0.17–0.33],0.22 [0.16-0.3]
3,Global,2017,1 800 000 [1 300 000–2 400 000],0.24 [0.18–0.32],0.24 [0.18–0.34],0.23 [0.17-0.32]
4,Global,2016,1 800 000 [1 300 000–2 400 000],0.25 [0.18–0.34],0.25 [0.18–0.35],0.24 [0.18-0.33]
...,...,...,...,...,...,...
206,Western Pacific,1994,140 000 [87 000–180 000],0.09 [0.05–0.12],0.13 [0.08–0.17],0.05 [0.03-0.06]
207,Western Pacific,1993,50 000 [32 000–67 000],0.03 [0.02–0.04],0.05 [0.03–0.06],0.02 [&lt;0.01-0.02]
208,Western Pacific,1992,40 000 [25 000–53 000],0.03 [0.02–0.03],0.04 [0.02–0.05],0.01 [&lt;0.01-0.02]
209,Western Pacific,1991,30 000 [19 000–40 000],0.02 [0.01–0.03],0.03 [0.02–0.04],&lt;0.01 [&lt;0.01-0.01]
210,Western Pacific,1990,23 000 [14 000–31 000],0.02 [&lt;0.01–0.02],0.02 [0.02–0.03],&lt;0.01 [&lt;0.01-&lt;0.01]

In [94]:
df.columns              # viweing the total number of columns present in a dataset

Index(['Unnamed: 0', 'Unnamed: 1', 'Number of new HIV infections',
       'New HIV infections (per 1000 uninfected population)',
       'New HIV infections (per 1000 uninfected population).1',
       'New HIV infections (per 1000 uninfected population).2'],
      dtype='object')

In [95]:
df[ 'New HIV infections (per 1000 uninfected population)']=df[ 'New HIV infections (per 1000 uninfected population)'].str.replace(r"\[.*\]","")

In [96]:
df['New HIV infections (per 1000 uninfected population).1']=df['New HIV infections (per 1000 uninfected population).1'].str.replace(r"\[.*\]","")

In [97]:
df['New HIV infections (per 1000 uninfected population).2']=df['New HIV infections (per 1000 uninfected population).2'].str.replace(r"\[.*\]","")

In [98]:
df['Number of new HIV infections']=df['Number of new HIV infections'].str.replace(r"\[.*\]","")

In [99]:
df['New HIV infections (per 1000 uninfected population).2']=df['New HIV infections (per 1000 uninfected population).2'].str.replace(r"\&lt","")

In [100]:
#renaming drithe columns
df.rename(columns={'Unnamed: 0':'WHO region', 'Unnamed: 1':'Year'}, inplace = True)

    RESULTANT DATASET

In [101]:
df

,WHO region,Year,Number of new HIV infections,New HIV infections (per 1000 uninfected population),New HIV infections (per 1000 uninfected population).1,New HIV infections (per 1000 uninfected population).2
0,WHO region,Year,,Both sexes,Male,Female
1,Global,2019,1 700 000,0.22,0.23,0.21
2,Global,2018,1 700 000,0.23,0.24,0.22
3,Global,2017,1 800 000,0.24,0.24,0.23
4,Global,2016,1 800 000,0.25,0.25,0.24
...,...,...,...,...,...,...
206,Western Pacific,1994,140 000,0.09,0.13,0.05
207,Western Pacific,1993,50 000,0.03,0.05,0.02
208,Western Pacific,1992,40 000,0.03,0.04,0.01
209,Western Pacific,1991,30 000,0.02,0.03,;0.01
210,Western Pacific,1990,23 000,0.02,0.02,;0.01

# Exporting the cleaned datasets to excel

In [104]:
df1.to_excel('C:\\Users\\Anjali\\notebooks\\Untitled Folder\\HIV1.xlsx',index= False , header= True)   #dataset exported to excel file

In [105]:
df1

,WHO region,Year,Number of new HIV infections,New HIV infections (per 1000 uninfected population),New HIV infections (per 1000 uninfected population).1,New HIV infections (per 1000 uninfected population).2
1,Global,2019,1 700 000,0.22,0.23,0.21
2,Global,2018,1 700 000,0.23,0.24,0.22
3,Global,2017,1 800 000,0.24,0.24,0.23
4,Global,2016,1 800 000,0.25,0.25,0.24
5,Global,2015,1 900 000,0.26,0.26,0.26
...,...,...,...,...,...,...
206,Western Pacific,1994,140 000,0.09,0.13,0.05
207,Western Pacific,1993,50 000,0.03,0.05,0.02
208,Western Pacific,1992,40 000,0.03,0.04,0.01
209,Western Pacific,1991,30 000,0.02,0.03,;0.01
210,Western Pacific,1990,23 000,0.02,0.02,;0.01